### ISSUE TITLE
Python cannot see graphviz on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by sixsamuraisoldier** [pygraphviz/pygraphviz#143]
ImportError: No module named graphviz

However, I've installed both via sudo apt-get install and via pip install and running 'dot -V' gives me:
"dot - graphviz version 2.36.0 (20140111.2315)"

Any help?

Thanks in advance!

**Comment by azrdev** [comment]
@sixsamuraisoldier maybe you're confusing [python `graphviz`](https://pypi.python.org/pypi/graphviz/0.8.2) with [pygraphviz](https://pypi.python.org/pypi/pygraphviz/1.4rc1)

**Comment by mrintoul** [comment]
[This helped me](https://github.com/pygraphviz/pygraphviz/issues/54#issuecomment-316511342), although I'm not sure why.

**Comment by rossbar** [comment]
This should be fixed in pygraphviz-1.7 which was just recently released.

> This helped me, although I'm not sure why.

In older versions of pygraphviz, there was custom setup functionality that depended on `pkg-config`. This has all been removed in v1.7, and installing pygraphviz via pip should work out-of-the-box when Graphviz is installed via `apt`. See [the updated installation instructions](https://pygraphviz.github.io/documentation/stable/install.html#ubuntu-and-debian) for details.

If you run into problems installing pygraphviz on Ubuntu, please open a new issue with info on the Ubuntu version and how Graphviz was installed.
