### ISSUE TITLE
Not able to install pygraphviz 

### ISSUE THREAD

**Issue by NikhilBansal21** [pygraphviz/pygraphviz#156]
I am not able to install pygraphviz on windows 10 64 bit

I am running pip install --global-option=build_ext --global-option="-IC:\Program Files\Graphviz2.38\include" --global-option="-LC:\Program Files\Graphviz2.38\lib\release\lib" pygraphviz

![pygraphviz error](https://user-images.githubusercontent.com/16642277/39806788-635151ba-5398-11e8-8fb4-09c299706fcf.PNG)

**Comment by 98-f355-f1** [comment]
Same thing with me... trying to use networkx which uses graphviz.  I have graphviz installed. I have spent the whole day trying to resolve this.
OS: win 10
Py: 3.65

**Comment by diogolr** [comment]
Look at my comment there:

https://github.com/pygraphviz/pygraphviz/issues/74#issuecomment-413885258

**Comment by patriciars** [comment]
Hello

I have the same problem.
I installed graphviz using pip install
I have installed pygraphviz using winpython control center because using pip install I have an error 


![image](https://user-images.githubusercontent.com/25747552/53170828-d8924100-35bf-11e9-86bf-6e88e5bd06ab.png)


using winpython control center it's work and I can import the package in python;
But when I write G.layout()
I get the error

"Program neato not found in path."

What can I do?

**Comment by dschult** [comment]
Be careful... graphviz installed by pip is a python program. It is not GraphViz. You need GraphViz

**Comment by fraseg** [comment]
I managed to get past the include problem by changing setup.py to reference the paths to graphviz on my machine, for belt and braces I also set the PATH to point to both. Now it is failing on linking. @dshult please can you post to github a doc with instructions on how to install for windows 10 64 bit? I have spent all day trying to install I love the output so really want to use the module, please can you help?

**Comment by LACoderDeBH** [comment]
conda install graphviz worked for me

**Comment by rossbar** [comment]
Pygraphviz 1.7 was just released and it should be significantly more straightforward to install on Windows. Graphviz is still required, but Graphviz installation on Windows has also improved significantly since the OP - see [the updated installation guide](https://pygraphviz.github.io/documentation/stable/install.html#windows) for details. Patching the source code should no longer be required to build+install pygraphviz on Windows.

If you run into problems installing pygraphviz on Windows, please open a new issue with updated info on how Graphviz was installed on your system.

**Comment by LomNtetha** [comment]
I have the same problem any solution please, I am using ubuntu 22.04
