### ISSUE TITLE
Documented command for installing pygraphviz from dev is wrong

### ISSUE THREAD

**Issue by xiamaz** [pygraphviz/pygraphviz#221]
In the documentation for [installing development versions of graphviz](http://pygraphviz.github.io/documentation/pygraphviz-1.5/install.html#providing-path-to-graphviz) the following command is given:

```
python setup.py install --include-path=/usr/local/Cellar/graphviz/2.38.0/include/graphviz --library-path=/usr/local/Cellar/graphviz/2.38.0/lib
``` 

The command flag for include-path is wrong, as /graphviz is not needed and will generate an error if added even if the remaining path has been updated for the local config.

Fix:

The documented command should be:

```
python setup.py install --include-path=/usr/local/Cellar/graphviz/2.38.0/include --library-path=/usr/local/Cellar/graphviz/2.38.0/lib
```

**Comment by dschult** [comment]
This is an example, and is likely to work. I don't think the include-path is wrong.  It is in fact right most of the time. It is true that a shorter version may work also. But I don't think having this version will generate an error unless the include files are not in a graphviz directory within the include directory. 

You say the ending "/graphviz" generates an error if added. Can you compare the directory the include files were actually located with the path you used to generate the error?

Otherwise I think this is an excellent example and should not be changed.

**Comment by rossbar** [comment]
The most recent release (pygraphviz-1.7) has [updated installation docs](https://pygraphviz.github.io/documentation/stable/install.html#install) including procedures for finding the necessary headers/libs/binaries on most major platforms.

If you run into trouble with the updated installation procedures or the updated docs don't cover your use-case, please re-open this or open a new issue with updated info.
