### ISSUE TITLE
Question about equality of graphs when one graph is missing attributes

### ISSUE THREAD

**Issue by rossbar** [pygraphviz/pygraphviz#284]
Two AGraph instances are considered unequal if the attributes of any node or edge in the two graphs are not the same. However, if one graph has node/edge attributes that are not part of the other, the graphs are still considered equal.

```python
>>> nodes = [0, 1]
>>> A, B = pgv.AGraph(), pgv.AGraph()
>>> A.add_nodes_from(nodes)
>>> B.add_nodes_from(nodes)
>>> A == B  # Both graphs have nodes 0 and 1, neither with any attributes
True
>>> A.node_attr['color'] = 'red'
>>> B.node_attr['color'] = 'red'
>>> A == B  # The 'color' attribute is 'red' for all nodes in both graphs
True
>>> B.get_node(1).attr['color'] = 'blue'
>>> A == B  # The attributes for node 1 aren't the same between A and B, so A and B are not considered equal
False
>>> C = pgv.AGraph()
>>> C.add_nodes_from(nodes)
>>> A == C  # True, even though C doesn't have the same node attributes as A
True
```

A and C are considered equivalent by pygraphviz, but if you draw them, one will have a different coloring than the other. So the question is - should the node/edge attr consistency check extend to checking that the set of nodes/attributes are the same for different graphs?

**Comment by dschult** [comment]
I missed this in the flurry of activity lately! :)
Thanks @jarrodmillman for the nudge.  

equality of graphs used to be based on the dot string. But the dot string produced by `cgraph` depends on version, system, etc. PR #246 changed the equals dunder to look at the attributes in AGraph rather than the dot_string produced from it. But your tests suggest that the `__eq__` still doesn't work quite right.

Attributes are propagated to all nodes/edge once they are created on one -- with a default value system that I haven't nailed down yet. I'll take a look. :}

**Comment by dschult** [comment]
I figured out that the AGraph attribute dict-like (`ItemAttribute`) used for node and edge attributes doesn't yield any attributes that have the same value as the default value for that key. Presumably this is to reduce output size, but I'm not sure I agree with the API choice here.  It makes checking for equality of graphs difficult.

I'm thinking I will create an `iteritems`-like method called `to_attrdict` which creates a dict keyed by attribute name to the value of that attribute whether the value comes from a default value or an item specific value.

This should help to clean up the equals dunder. But might also ease checking attributes elsewhere(?).
