### ISSUE TITLE
update the FAQ

### ISSUE THREAD

**Issue by jarrodmillman** [pygraphviz/pygraphviz#311]
We should update the FAQ:
https://pygraphviz.github.io/documentation/latest/reference/faq.html

In particular, we may want to address why we can't make self-contained wheels.  That should briefly explain the situation, what needs to be done to fix it (in case anyone is willing to help), and link to:
- https://github.com/pygraphviz/pygraphviz/issues/167
- https://gitlab.com/graphviz/graphviz/-/issues/1808#note_403608643

Maybe the FAQ should be moved closer to (or be part of) the INSTALL information...or maybe at the top-level alongside INSTALL and REFERENCE.  It is pretty hidden now.

**Comment by rossbar** [comment]
> Maybe the FAQ should be moved closer to (or be part of) the INSTALL information

I agree. The FAQ deals only with installation issues so IMO it makes the most sense for this info to live in the installation doc. In 7fc4d94 I've `.. include`ed the FAQ in the installation doc so that it is directly embedded in the installation instructions (note that this means the FAQ shows up both in `install` and `reference`). LMK what you think - I'm happy to structure it in whichever way makes the most sense.
