### ISSUE TITLE
What is wc used for?

### ISSUE THREAD

**Issue by dotlambda** [pygraphviz/pygraphviz#332]
The program `wc` is mentioned in
https://github.com/pygraphviz/pygraphviz/blob/894a45b43aa8ec332758dc170f5a73cbef762a6e/pygraphviz/agraph.py#L1330

Should that be `gc`? But I can't find a reference to either in the rest of the codebase.

**Comment by dschult** [comment]
The command utilities that come with GraphViz include many that pygraphviz only passively supports.  The[ gc man page](https://linux.die.net/man/1/gc) says it is like that standard Linux tool wc only for graphs. The tool wc counts lines, words and characters. The tool gc counts nodes, edges and components (graph components is where it gets its name).

I am pretty sure the list should have gc and not wc.  But you should probably be looking at GraphViz docs rather than pygraphviz docs.

**Comment by dotlambda** [comment]
I know what the difference between `wc` and `gc` is. But to my understanding, the referenced list should only contain programs that are used elsewhere in the code. Neither `wc` nor `gc` are.

**Comment by dschult** [comment]
The `_get_prog` and `_run_prog` methods can run any graphviz program.
Perhaps they shouldn't. But the historical reason for the list is probably they we
were debugging an issue the graphviz not including all their programs in a release
so we wanted t keep track of what was available. `_get_prog` is a pretty safe place 
to put that list. But as with all collections of information, it may be wrong or get
out of date.  Perhaps we should remove that list.

**Comment by rossbar** [comment]
> Perhaps they shouldn't. But the historical reason for the list is probably they we
were debugging an issue the graphviz not including all their programs in a release
so we wanted t keep track of what was available. 

My vote would be to keep the listing there as long as pygraphviz is based on the Graphviz cmd line interface. I think it is useful to make sure that the bridge from pygraphviz to Graphviz works for all the functions Graphviz provides, even if the functions aren't necessarily very important for users. I think down the line, if/when it becomes recommended to switch to Graphviz's library interface, this will no longer be a problem.

**Comment by dotlambda** [comment]
If the listing is kept, `wc` should be removed or replaced with `gc`.
