### ISSUE TITLE
Unable to install pygraphviz on airflow

### ISSUE THREAD

**Issue by skapoorosts** [pygraphviz/pygraphviz#401]
Team,
I'm getting following error while installing 'pygraphviz' library on airflow:

aws-mwaa-local-runner]$ ./mwaa-local-env test-requirements
Container amazon/mwaa-local:2.0.2 exists. Skipping build
Installing requirements.txt
Collecting graphviz==0.19.1
  Downloading graphviz-0.19.1-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 KB 2.7 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement pygraphviz==1.9 (from versions: 0.34, 0.35, 0.36, 0.37, 0.99, 0.99.1, 1.0rc1, 1.0rc2, 1.0rc3, 1.0rc4, 1.0rc5, 1.0rc6, 1.0, 1.1rc1, 1.1, 1.2, 1.3rc1, 1.3rc2, 1.3, 1.3.1, 1.4rc1, 1.5, 1.6rc1, 1.6, 1.7rc1, 1.7rc2, 1.7, 1.8rc1, 1.8)
ERROR: No matching distribution found for pygraphviz==1.9

Here is the contents of requirements.txt (python dependencies which i am using):

cat ./dags/requirements.txt 
graphviz == 0.19.1
pygraphviz == 1.9

Can you please provide me an assitance to fix this issue?

Thanks,
Sumit

**Comment by rossbar** [comment]
pygraphviz 1.9 is [available on pypi](https://pypi.org/project/pygraphviz/), so I'd double check that you are installing from the official python package index.

It looks like there have been some hiccups on pypi.org today: https://status.python.org/. Maybe try again and see if the problem hasn't been resolved?

**Comment by skapoorosts** [comment]
I tried today and get the same error. I think the problem with the dependent python libararies which are needed for 'pygraphviz'.
Can you please tell mem what are the dependent libraires do i need to include for 'pygraphviz' to be working.

Here is the contents in my requirements.txt:

graphviz == 0.19.1
pygraphviz == 1.9
pkg-config == 1.5

Also can you please let me know if there is any .whl distribution for this library. If we have .whl that can solve the probkem if in corporate that into requirementst.txt Please advise!

**Comment by rossbar** [comment]
> I tried today and get the same error. I think the problem with the dependent python libararies which are needed for 'pygraphviz'.

If you're still getting the ` ERROR: No matching distribution found for pygraphviz==1.9` message, then it's not a dependency issue. If it were a dependency issue you'd be past this stage and get a different error when the wheel tried to build locally, most likely something about missing header files. Do you by any chance have the `--no-index` flag somewhere in your pip install script? Otherwise I'm not sure why pygraphviz==1.9 can't be found.

>  Can you please tell mem what are the dependent libraires do i need to include for 'pygraphviz' to be working.

There seems to be another point of confusion - `pygraphviz` depends on [graphviz](https://graphviz.org/), *which is different from the [python graphviz package](https://graphviz.readthedocs.io/en/stable/manual.html)*. The graphviz that `pygraphviz` depends on is not a Python project and thus is not pip-installable. See the [installation instructions](https://pygraphviz.github.io/documentation/stable/install.html) for more details.

> Also can you please let me know if there is any .whl distribution for this library. If we have .whl that can solve the probkem if in corporate that into requirementst.txt Please advise!

No, there is currently no wheel due to the nature of the Graphviz dependency - see #167 for further details.

**Comment by rossbar** [comment]
Hopefully this has been addressed in the above explanation - the name collision between the main graphviz library and the Python graphviz package is unfortunate, but there's nothing we can do about it within pygraphviz. I will close this as resolved, but if further followup is needed please feel free to reopen with the latest info.
