### ISSUE TITLE
AGraph.size() vs graph size attribute: inconsistency and confusion

### ISSUE THREAD

**Issue by camilaran** [pygraphviz/pygraphviz#49]
AGraph class method "size()" does not correspond to the definition of attribute "size" in graphviz 'dot' language.
Whereas in 'dot', size is a graphical attribute, in pygraphviz it returns the number of edges.
This behavior is confusing and undesirable because: 
1. the behavior of size() is not needed as it can be obtained from len(G.edges())
2. the 'size' attribute in a dot file cannot be accesed, which in my case is a major drawback
3. consistency is lost between graphviz 'dot'  and pygraphviz semantics

Thank you for your work, your library has helped me a lot.

**Comment by camilaran** [comment]
I have just found in the example file:
"/usr/share/doc/python-pygraphviz/examples/attributes.py"
  the 'graph_attr[]' method, which apparently can be used to read all the graph attributes from a dot file. That's nice ! This solves my problem.

However, this method is not well documented, it would be nice to put it in into the help function output. In addition, I still think the "size()" method is not needed and is confusing.

**Comment by hagberg** [comment]
We also have number_of_edges() which is the same as size() and more descriptive.  

I'm sure the size() method is included since at one point there was a goal to make the PyGraphviz and NetworkX API similar.  I don't think that is desirable anymore so I don't have a problem with deprecating size() if it is confusing.
