### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by xmnlab** [pygraphviz/pygraphviz#61]
Hi everyone,

I've installed pygraphviz from git [1] .. and when I import the lib I receive this message error:

``` python
>>> import pygraphviz as pgv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/__init__.py", line 32, in <module>
    from . import release
ImportError: cannot import name 'release'
```

Any idea?

My best regards,

[1] pip3 install  git+git://github.com/pygraphviz/pygraphviz.git

**Comment by jdrudolph** [comment]
having the same issue after installing `pygraphviz-1.3rc2`  from git as described in #60 with `python3`

**Comment by hagberg** [comment]
Are there any errors during the install?  I can't reproduce this error.

**Comment by xmnlab** [comment]
Sorry, no errors during the install

**Comment by obust** [comment]
same error here

**Comment by hagberg** [comment]
I'm not sure what is causing this error.  Please post error messages so we can debug.

**Comment by JacksonLLee** [comment]
Same issue here. I'm on Ubuntu 14.04 with Python 3.4. After running `sudo apt-get install graphviz libgraphviz-dev pkg-config`, `pygraphviz` v1.3.1 was installed through `pip` (no errors during installation). The import error:

```python
>>> import pygraphviz as pgv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/__init__.py", line 32, in <module>
    from . import release
ImportError: cannot import name 'release'
```

The dev version 1.4 at https://github.com/pygraphviz/pygraphviz/commit/245fc9507a9e40f8c35762dd5073e42edb0388d3 also gives the same import error with `import pygraphviz as pgv`.

Any ideas how to solve the import issue?

Not sure how relevant this is, but out of curiously I also tried `import pygraphviz`.
Strangely, v1.3 from `pip` and v1.4 from github as referenced above give different errors...

v1.3.1:

```python
>>> import pygraphviz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/agraph.py", line 26, in <module>
    from . import graphviz as gv
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
  File "/usr/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: /usr/local/lib/python3.4/dist-packages/pygraphviz/_graphviz.cpython-34m.so: undefined symbol: Agundirected
```

dev v1.4:

```python
>>> import pygraphviz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/agraph.py", line 26, in <module>
    from . import graphviz as gv
  File "/usr/local/lib/python3.4/dist-packages/pygraphviz/graphviz.py", line 293, in <module>
    AGRAPH = _graphviz.AGRAPH
AttributeError: 'module' object has no attribute 'AGRAPH'
```

Are we supposed to never use the plain `import pygraphviz` for some reason? Maybe I've missed it somewhere in the documentation...

Thanks in advance for the help!

**Comment by djordon** [comment]
@JacksonLLee I ran into the same problem on the same platform (although I didn't try the dev version). The following worked for me, taken from https://github.com/pygraphviz/pygraphviz/issues/71#issuecomment-138999823:
```
pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
```
Hope this helps.

**Comment by fnielsen** [comment]
@djordon's reinstall worked for me too after problem with the present pip version:

    sudo pip2 install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/" --upgrade --force-reinstall

**Comment by rishidabre** [comment]
Thanks @fnielsen , this worked for me too!

**Comment by riasat** [comment]
@fnielsen I got the following error

`rabir@rabir:~/Documents$ sudo pip2 install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/" --upgrade --force-reinstall
/usr/local/lib/python2.7/dist-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
The directory '/home/rabir/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/rabir/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pygraphviz
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading pygraphviz-1.3.1.zip (123kB)
    100% |████████████████████████████████| 133kB 2.8MB/s 
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 412, in run_egg_info
    self.setup_py, self.name,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/local/lib/python2.7/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)`

**Comment by fnielsen** [comment]
@riasat I am not sure this is a pygraphviz error. It sees to have been discussed here https://stackoverflow.com/questions/42029545/pip-is-error-typeerror-call-takes-exactly-2-arguments-1-given I would suggest an update of pip and if that does not work then try another version of setuptools.

**Comment by transfluxus** [comment]
got the same problem.
tried version 1.4rc1 and 1.3.1
using pip 9.0.1 and setuptools 34.3.3
getting:
```dlopen(/Users/wack/venv/lib/python2.7/site-packages/pygraphviz/_graphviz.so, 2): Library not loaded: /opt/local/lib/libltdl.7.dylib
  Referenced from: /usr/local/lib/libcgraph.6.dylib
  Reason: image not found
```
didn't try the solution suggested above. would be nice to have something without sudo :)

**Comment by fnielsen** [comment]
"Referenced from: /usr/local/lib/libcgraph.6.dylib" seems to be another kind of error, not "the same problem".

**Comment by transfluxus** [comment]
I figured it out. maybe that graphviz is a fundamental requirement should be more present. it might be obvious for some... for others not known. it's on the very bottom of some documentation page.

works really nice! ... just trying simple things till now.

**Comment by xtaraim** [comment]
Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
install microsoft c++ 14.0
unique solution to install graphiz
pip install graphiz
no need to define path or anything.
